### ISSUE TITLE
Transient lit mode output is strange

### ISSUE THREAD

**Issue by Opacitation** [Enigmatisms/AdaPT#9]
Hi! I'm interested in rendering and have been learning taichi lang for a while. I played with your renderer several days ago and I think the outputs of transient lit mode is not so correct. It looks kinda strange if you actually use it in scenes like bunny and so on. Like in bunny scene, some places are lit too early, like those colored walls.

**Comment by Enigmatisms** [comment]
Yeah... I found that, too. I checked my implementation and, well, I guess there certainly is some refactoring work to do. It seems that the duration calculation for `transient_lit` mode is utterly wrong. It should have been based on projecting vertices starting from the emitter directly to the camera plane. However, I am busy with some other stuffs recently, therefore might not be able to correct this. So feel free to make a PR if you correct it yourself, it would be much appreciated.

**Comment by Opacitation** [comment]
Thanks. I will try if I got time. Should I leave this issue unclosed?

**Comment by Enigmatisms** [comment]
It's fine to leave it be. This issue will be closed when the bug is fixed.

**Comment by Enigmatisms** [comment]
This is fixed in the lastest commit (not release).
